---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by joyne.
--- DateTime: 08.09.2021 14:55
---

local mymodule = {}

function mymodule.sayhi()
    print("Hi there! Hello from module")
end

return mymodule
